### ISSUE TITLE
[ISSUE] Some bad behaviours in the GUI [Qobuz]

### ISSUE THREAD

**Issue by th2j** [AF-1/lms-ratingslight#2]
Hello

I have noticed a few problems in the GUI
Can you look at them please ?
Thanks

**Problem 1 :**

**1a. In Material Skin**

I have rated two albums
when i go to "my music" "rated tracks" "5 stars artists" i see :
- various artist
- the two album artists
- all albums

but if i rate for example the album "Cat Power sings Dylan" from "Cat Power"
when i go to "my music" "rated tracks" "5 stars artists" i see :
- various artist
- the two album artists
- Bob Dylan

So i don't see "Cat Power" but "Bob Dylan" instead who is the composer
And the entry "Bob Dylan" is empty
And "All albums" has disappeared

**1b. In default Skin**

With the same 2 albums + "Cat Power sings Dylan"

when i go to "my music" "rated tracks" "5 stars artists" i see :
- various artist
- the two album artists
- Bob Dylan
- Cat Power
- All Albums

but "Bob Dylan" behaves like "All Albums"
"Cat Power" and "All albums" are empty

**Problem 2 :**

**2a. In Material Skin**

I have rated two albums
when i go to "my music" "rated tracks" "5 stars artists" i see :
- various artist
- the two album artists
- all albums

If i had another album, "All albums" disappears

**2b. In default Skin**

I have rated two albums
when i go to "my music" "rated tracks" "5 stars artists" i see :
- various artist
- the two album artists
- all albums

If i had another album, i see :
- various artist
- the 3 album artists
- all albums

but "all albums" is empty
and the third artist added behave like "all albums"

**Problem 3 :**

3a. In Material Skin

I have rated two albums
when i go to "my music" "rated tracks" "5 stars genres" i see the two genres listed :
- Alternatif et Indé
- Trip Hop

but "Alternatif et Indé" lists the two artists instead of one, and the artist who is showing but not "Alternatif et Indé" is empty
And i don't see "All albums"

**Comment by AF-1** [comment]
I need to know _at least_  your LMS version. RL does not create those menus but asks LMS to create them. I'll take a look.

**Comment by th2j** [comment]
I was on 8.2 or 8.3
i don't remember because i move to 8.4 this afternoon
but the problems are still here

Thanks

**Comment by AF-1** [comment]
I haven't been able to reproduce your problems so far. The fact that you have empty items sometimes is a known issue (see footnote 2 on GitHub page). 
But to further investigate I'd need those albums (tracks), only for their metadata/tags. Maybe I could reproduce it then.

**Comment by th2j** [comment]
the albums are on qobuz
you can subscribe for a free month account to reproduce the problem.

here is the url to put them on LMS : 

https://play.qobuz.com/album/f9n2x2hi3b7oc
https://play.qobuz.com/album/5414939696374
https://play.qobuz.com/album/jccu13nd9qpxa

**Comment by th2j** [comment]
To be accurate, the albums from Qobuz are integrated in LMS library with the plugin "Music online library integration"

**Comment by michaelherger** [comment]
@th2j can you reproduce the same issue with local tracks? Remote or local could just be a red herring, complicating things more than necessary.

**Comment by th2j** [comment]
> @th2j can you reproduce the same issue with local tracks? Remote or local could just be a red herring, complicating things more than necessary.

So i tried with the 3 same albums in local (downloaded from qobuz)
And everything is OK

Except that i can see "Bod Dylan" in "5 stars artists", who is the composer. And there is no tracks under that entry
But it is not a big deal

**Comment by michaelherger** [comment]
Could you please share the metadata of one of these tracks as reported in the track info menu "View Tags"? Should be interesting to see how it compares with the metadata we get from the online service.

**Comment by th2j** [comment]
> Could you please share the metadata of one of these tracks as reported in the track info menu "View Tags"? Should be interesting to see how it compares with the metadata we get from the online service.

here is the tags of these local files :
https://www.dropbox.com/scl/fi/pqbtls0lfpf83tou2bsli/Tags-Local-Files.odp?rlkey=uhos1z1tfc0tq3mbnwfmyine3&dl=0

**Comment by michaelherger** [comment]
Hmm... that's very close to what we get over the API:

```
composer => { id => 365_921, name => "Bob Dylan" },
media_number => 1,
performer => { id => 34_526, name => "Cat Power" },
performers => "Rob Schnapf, Mixer - Bob Dylan, Composer, Author - Mark Chalecki, MasteringEngineer - Cat Power, MainArtist - Andrew Slater, Producer - Matt Schuessler, Engineer - Sony/ATV Music Publishing (UK), MusicPublisher - Universal Tunes, MusicPublisher - Ollie Nesham, Engineer - Eduardo Puhl, Engineer - Pete Panagaris, Engineer",
title => "She Belongs To Me",
track_number => 1,
version => "Live at the Royal Albert Hall",
```

We do not use the `performers` field. But the main artist and the composer are the same.

Would you mind scanning a library with the track both from online as well as the downloaded version? Then send me the resulting `library.db` (https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a)?

**Comment by th2j** [comment]
> Hmm... that's very close to what we get over the API:
> 
> ```
> composer => { id => 365_921, name => "Bob Dylan" },
> media_number => 1,
> performer => { id => 34_526, name => "Cat Power" },
> performers => "Rob Schnapf, Mixer - Bob Dylan, Composer, Author - Mark Chalecki, MasteringEngineer - Cat Power, MainArtist - Andrew Slater, Producer - Matt Schuessler, Engineer - Sony/ATV Music Publishing (UK), MusicPublisher - Universal Tunes, MusicPublisher - Ollie Nesham, Engineer - Eduardo Puhl, Engineer - Pete Panagaris, Engineer",
> title => "She Belongs To Me",
> track_number => 1,
> version => "Live at the Royal Albert Hall",
> ```
> 
> We do not use the `performers` field. But the main artist and the composer are the same.
> 
> Would you mind scanning a library with the track both from online as well as the downloaded version? Then send me the resulting `library.db` (https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a)?

The library.db have been posted,
Thanks

**Comment by michaelherger** [comment]
I'll really have to review what exactly LMS is doing with the `ARTIST` vs. `TRACKARTIST` and `ALBUMARTIST`. Because here's what I've found in your library (`remote=1` is the online version):

| remote | title | role | name |
| --- | --- | --- | --- |
| 1 | Cat Power Sings Dylan: The 1966 Royal Albert Hall Concert | Artist | Cat Power |
| 1 | Cat Power Sings Dylan: The 1966 Royal Albert Hall Concert | Composer | Bob Dylan |
| 0 | Cat Power Sings Dylan: The 1966 Royal Albert Hall Concert | Track Artist | Cat Power |
| 0 | Cat Power Sings Dylan: The 1966 Royal Albert Hall Concert | Album Artist | Cat Power |
| 0 | Cat Power Sings Dylan: The 1966 Royal Albert Hall Concert | Composer | Bob Dylan |

So for the local file there are explicit track/album artists defined, whereas the online version only has the artist. The latter I thought was considered the album artist if none other was defined.

**Comment by th2j** [comment]
hello,

when i make a search, for exemple "radiohead",
there is no result if i click on "radiohead" in albums list :

![Capture d’écran du 2023-12-03 09-42-30](https://github.com/AF-1/lms-ratingslight/assets/75980231/b4b33efb-5cb6-401b-82fd-bcd7ecdaa73f)

is it relative to the lack of ALBUMARTIST for online source ?
