### ISSUE TITLE
[ISSUE] Previously rated but unplayed songs have their rating set to 100 after playing

### ISSUE THREAD

**Issue by TaurusI76** [AF-1/lms-ratingslight#3]
## DESCRIBE THE BUG
After migrating from TrackStat ratings to RatingsLight, there might be songs in the library that have a APC PlayCount of 0, but they have a Rating set.
If these tracks are played, the Rating is set to 100 after playing (overriding the previous rating).

Example:
Track has a APC PlayCount of 0 (the PlayCount can be 1)
Rating is 60
Play the track (or skip to > 50%), the track gets marked as played, APC PlayCount is set to 1, APC Last Played is set to the correct date.
The Rating is now 100.

<br><br>
## TO REPRODUCE
1. Create a Dynamic Playlist or Library View that only contains songs with a minimum rating of 0.5 stars, but only unplayed tracks
2. Play any song in that playlist/library.
3. Observe rating before and after playing.

<br><br>
## EXPECTED BEHAVIOR
The previous rating is preserved or adjusted accordingly (e.g. increased after playing).

<br><br>
## VERSION INFO
* LMS version: 8.4.1
* OS (version): Synology DSM 7.2.1-69057 Update 3
* Plugin version: 2.6.3
* Web skin/controller: LMS Default
* Browser (version): Google Chrome Version 122.0.6261.70

**Comment by AF-1** [comment]
I'm guessing that you have enabled **Automatic Rating** (_dynamic rating_) in APC (disabled by default).
If APC considers a track played (per your settings) **and** you have auto-rating enabled, APC will ask RL to set the rating value it has calculated (RL just executes and has no part in this otherwise).
In the APC settings there's a setting called _Dynamic automatic rating change_ (I'm probably going to rename this). It gives you _some_  control over much the algorithm changes the rating value. The tricky part (as mentioned in the settings description) is that the smaller this value, the bigger the _dynamic_ auto rating change. BTW the previous play count is not relevant to how auto-rating works.
If you want absolute control, I suggest _linear_ auto rating. It will always change the rating _exactly_ by the value you set in the prefs.
For more details please see the APC GitHub FAQ or the APC settings descriptions in the _automatic rating_ submenu.

**Comment by TaurusI76** [comment]
Yes, dynamic rating is enabled.
But the Dynamic automatic rating change value is set to the max (8), so I
still don't understand why there would be such a drastic change - it
doesn't make any sense to me. And it always goes to 100, whether the
previous rating was 10, 60 or 80.
And it doesn't set the default rating value that I configured either, it
just sets it to 100.

Couldn't you adjust the algorithm in the case when a previous rating is
already set?

**Comment by AF-1** [comment]
I can't reproduce your issue: dynamic auto-rating for *rated* tracks (e.g. 60) and baseline rating for *previously unrated* tracks work as expected here (APC version here 1.4.8, LMS 9). There's no evidence that the plugin or algorithm are not working properly.
Assuming that you don't have TrackStat installed at the moment, maybe there's a problem with your library database.
Please check the *server log* for related messages. You can also set the debug level of APC to `debug` to get more information.


BTW I posted some [**example results**](https://github.com/AF-1/lms-alternativeplaycount/wiki/Dynamic-auto%E2%80%90rating-%E2%80%90-example-results-of-the-algorithm) of how the `dynamic` auto-rating algorithm works.

**Comment by TaurusI76** [comment]
Thanks for your explanations & examples.
I did a library wipe & rescan and reimported all ratings. Now the dynamic
rating seems to work as it should.
TrackStat was not installed (disabled in the plugins config).
It seems that there was a problem with my database.

**Comment by TaurusI76** [comment]
Hey, I have to follow up on this bug. I think I narrowed down the issue. Can you try if you get the same behavior as me?

- Set Automatic Rating to Dynamic rating in APC (this might be more of an APC bug than RatingsLight)
- The value of Dynamic automatic rating change doesn't matter
- Find a track that has APC play count of 0 (never played)
- Manually set the track's rating to 60 or any other value than 100 before playing it.
- Play the track and wait until it's marked as played.
- The track rating is now 100.

If you set it to Linear rating, the track rating is 61 if it was 60 before (seems correct).

**Comment by AF-1** [comment]
Thank you for the detailled information.
It concerns APC, RL only executes the rating command. 

The assumption in APC was that un**played** tracks were also un**rated** - not unreasonable but not always true either. 
**If** you had baseline rating enabled (default = 60), the rating of an unplayed track (no matter its current rating value) would increase by the baseline rating value. Your example: 60 (current) + 60 (baseline) = 120, capped at 100. That's what you saw.

I've changed this in APC 1.5.3. Now only tracks that are un*played* ***and*** un*rated* get the baseline rating.
