### ISSUE TITLE
[ISSUE] Rating Light isn't showing up in the menu anymore

### ISSUE THREAD

**Issue by renemgit** [AF-1/lms-ratingslight#6]
No clue why but suddenly the Rating menu button is gone...

![2024-09-11_09-19-15](https://github.com/user-attachments/assets/4b078223-d4b2-4495-9047-9f2cc0e5ab6c)

Maybe because the latest 8.52 version?

![2024-09-11_09-20-36](https://github.com/user-attachments/assets/07ab2ca1-31f1-4340-a107-17d597e463da)

Kind regards René

**Comment by renemgit** [comment]
So after a while everything it up and running. Maybe something with an update and caching thought.

**Comment by AF-1** [comment]
So it's solved then? If so, let me know and we can close the issue. Thanks.

**Comment by renemgit** [comment]
Yes it’s working now again.

It’s a really good plugin, thanks.



Kind regards, René Mulder
